# Generated by Django 6.0.3 on 2026-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default='all', max_length=10)),
                ('candidate_metadata', models.JSONField(default=dict)),
                ('transcript', models.TextField(blank=True)),
                ('conversation_history', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('final_report', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
