from ai_services.prompts.speaking_prompt import (
    IELTS_CONVERSATION_PROMPT,
    IELTS_CONVERSATION_PROMPT_PART1,
    IELTS_CONVERSATION_PROMPT_PART2,
    IELTS_CONVERSATION_PROMPT_PART3,
    IELTS_EVALUATION_PROMPT,
    IELTS_EVALUATION_PROMPT_PART1,
    IELTS_EVALUATION_PROMPT_PART2,
    IELTS_EVALUATION_PROMPT_PART3,
)
from ai_services.prompts.writing_task1_prompt import IELTS_TASK_1_EXAMINER_PROMPT
from ai_services.prompts.writing_task2_prompt import IELTS_TASK_2_EXAMINER_PROMPT

__all__ = [
    "IELTS_CONVERSATION_PROMPT",
    "IELTS_CONVERSATION_PROMPT_PART1",
    "IELTS_CONVERSATION_PROMPT_PART2",
    "IELTS_CONVERSATION_PROMPT_PART3",
    "IELTS_EVALUATION_PROMPT",
    "IELTS_EVALUATION_PROMPT_PART1",
    "IELTS_EVALUATION_PROMPT_PART2",
    "IELTS_EVALUATION_PROMPT_PART3",
    "IELTS_TASK_1_EXAMINER_PROMPT",
    "IELTS_TASK_2_EXAMINER_PROMPT",
]
