# Generated by Django 6.1.1 on 2026-09-14 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(blank=True, default='Cambridge', max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('variant', models.CharField(default='academic', max_length=20)),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='exam-sources/')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='exam-images/')),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('part_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='exam-audio/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=60)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='exams.book')),
            ],
            options={
                'ordering': ['book', 'test_number', 'part_number'],
                'unique_together': {('book', 'test_number', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exams.book')),
            ],
            options={
                'ordering': ['book', 'number'],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(default=3600)),
                ('transfer_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=40)),
                ('is_published', models.BooleanField(default=False)),
                ('band_table_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exams.examtest')),
            ],
            options={
                'ordering': ['test', 'skill'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('mode', models.CharField(choices=[('exam', 'Exam'), ('practice', 'Practice')], default='exam', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_section', models.PositiveSmallIntegerField(default=1)),
                ('audio_started_at', models.DateTimeField(blank=True, null=True)),
                ('audio_section_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('band_table_version', models.CharField(blank=True, max_length=20)),
                ('integrity_events', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exams.module')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerKeySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exam-answer-sheets/')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('ocr_answers', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.JSONField(blank=True, default=dict)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_answer_sheets', to=settings.AUTH_USER_MODEL)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheet', to='exams.module')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prompt_text', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.module')),
            ],
            options={
                'ordering': ['module', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('value', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(null=True)),
                ('awarded_marks', models.PositiveSmallIntegerField(default=0)),
                ('mark_reason', models.CharField(blank=True, max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.question')),
            ],
            options={
                'ordering': ['attempt', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('instruction_text', models.TextField(blank=True)),
                ('first_question', models.PositiveSmallIntegerField()),
                ('last_question', models.PositiveSmallIntegerField()),
                ('word_limit', models.CharField(blank=True, max_length=32)),
                ('select_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('options_reusable', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_bbox', models.JSONField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='exams.groupimage')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.questiongroup'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('first_question', models.PositiveSmallIntegerField(default=1)),
                ('last_question', models.PositiveSmallIntegerField(default=1)),
                ('passage_html', models.TextField(blank=True)),
                ('passage_paragraphs', models.JSONField(blank=True, default=list)),
                ('transcript_text', models.TextField(blank=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='exams.audioasset')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='exams.section'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['skill', 'is_published'], name='exams_modul_skill_b0aab4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('test', 'skill')},
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'module', 'status'], name='exams_attem_user_id_7c39fc_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', '-submitted_at'], name='exams_attem_user_id_e88ff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('module', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('section', 'order')},
        ),
    ]
