# Generated by Django 6.1.1 on 2026-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_importjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerkeysheet',
            name='ocr_answers',
        ),
        migrations.AddField(
            model_name='answerkeysheet',
            name='proposal_source',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='answerkeysheet',
            name='proposed_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
