# Generated by Django 6.1.1 on 2026-09-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_answerkeysheet_ocr_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.question'),
        ),
    ]
