# Generated by Django 6.1.1 on 2026-09-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_attemptanswer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='exam-passages/')),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_pages', to='exams.section')),
            ],
            options={
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
