# Generated by Django 6.1.1 on 2026-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_passagepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerkeysheet",
            name="confirmed",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="answerkeysheet",
            name="evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="answerkeysheet",
            name="revealed",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="answerkeysheet",
            name="verification_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("human", "Every answer checked by a person"),
                    (
                        "blind",
                        "Self-checks passed; a person checked only the flagged answers",
                    ),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="answerkeysheet",
            name="image",
            field=models.ImageField(blank=True, upload_to="exam-answer-sheets/"),
        ),
    ]
