# Generated by Django 6.0.3 on 2026-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=10)),
                ('prompt', models.TextField()),
                ('essay_text', models.TextField()),
                ('topic_image_url', models.URLField(blank=True, null=True)),
                ('scores', models.JSONField(default=dict)),
                ('examiner_comments', models.TextField(blank=True)),
                ('corrections', models.JSONField(default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
