# Generated by Django 6.0.3 on 2026-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiconfiguration_enabled_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingquestion',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='cue_card',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='topic',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
